n = int(input("Please tell me your age: "))
print(f"You are currently {n} years old.")
print(f"n 10 years, you'll be {n+10} years old")
print(f"n 20 years, you'll be {n+20} years old")
print(f"n 30 years, you'll be {n+30} years old")